config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookings
  resources :cats
  root 'cats#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :cat
end

app/models/cat.rb
class Cat < ApplicationRecord
  has_many :bookings
end

app/models/gender.rb
class Gender
  MALE = false
  FEMALE = true

  def self.names
    {
      MALE => "male",
      FEMALE => "female"
    }
  end
  
  def initialize(bool)
    @bool = bool
  end

  def name
    Gender.names[@bool]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:starts_at, :ends_at)
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name, :age, :color, :gender, :image_url, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :starts_at %>
    <%= f.datetime_select :starts_at %>
  </div>

  <div class="field">
    <%= f.label :ends_at %>
    <%= f.datetime_select :ends_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <!-- <thead>
    <tr>
      <th>Starts at</th>
      <th>Ends at</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.starts_at %></td>
        <td><%= booking.ends_at %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', cats_path %> 

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Starts at:</strong>
  <%= @booking.starts_at %>
</p>

<p>
  <strong>Ends at:</strong>
  <%= @booking.ends_at %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', cats_path %>

app/views/cats/_form.html.erb
<%= form_for(cat) do |f| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
      <div class="line">
       <%= f.label :gender %>
     </div>
       <span class="option">Male <span><%= f.radio_button :gender, "m" %></br>
       <span class="option">Female <span><%= f.radio_button :gender, "f" %></br>
    </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Cats</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Color</th>
      <th>Gender</th>
      <th>Image url</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.name %></td>
        <td><%= cat.age %></td>
        <td><%= cat.color %></td>
        <td><%= cat.gender %></td>
        <td><%= image_tag cat.image_url %></td>
        <td><%= cat.description %></td>
        <td><%= cat.price %></td>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cat.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @cat.age %>
</p>

<p>
  <strong>Color:</strong>
  <%= @cat.color %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @cat.gender %>
</p>

<p>
  <%= image_tag @cat.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cat.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cat.description %>
</p>

<%= link_to 'Booking page', new_booking_path %>



<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <!-- <ul class="nav navbar-nav">
      <li><%= link_to "Cats", cats_path %></li>
    </ul> -->
    <ul class="nav navbar-nav navbar-right">
      <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %> </li>
      <% else %>
          <li><span class="navbar-text"><%= current_user.email %></span></li>
          <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
    <% end %>
    </ul>
  </nav>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catguest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render "layouts/header" %>
<h1>CAT GUEST</h1>

<main class="container">
    <%= yield %>
</main>
  </body>
</html>